services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_user_pass
      POSTGRES_DB: practicalms
    restart: always
    volumes:
      - ./.containers/database:/var/lib/postgresql
    ports:
      - 5432:5432
